apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: camillamartins/docker-linuxtips:1.0
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: "64Mi"
              cpu: "0.1"

          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 8080
      protocol: TCP
      name: http
      nodePort: 30000
  type: NodePort